#
# CI build that assembles artifacts and runs tests.
# If validation is successful this workflow releases from the main dev branch.
#
# - skipping CI: add [skip ci] to the commit message
# - skipping release: add [skip release] to the commit message
#
name: CI

on:
  push:
    branches:
      - main
    tags:
      - 3.*
  pull_request:
    branches:
      - main

jobs:

  #
  # Main build job
  #
  build:
    runs-on:  ubuntu-latest

    steps:

    - name: 1. Check out code
      uses: actions/checkout@v2 # https://github.com/actions/checkout

    - name: 2. Set up Java 8
      uses: actions/setup-java@v1 # https://github.com/actions/setup-java
      with:
        java-version: 8

    - name: 3. Build
      run: |
        git describe --tags
